### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by aardes** [freeseek/gtc2vcf#23]
Dear Giulio,

Thanks a lot for such nice workfellow for the conversion of the gtc files to vcf.

because of some limitations, I wasn't able to install everything and tried to convert the whole package to a docker and I failed here too.

Do you have any plane to make a docker container that does the whole process?

Really appreciate it.

Regards

**Comment by freeseek** [comment]
Dear Aardes,

You might have some luck using the binaries provided [here](http://software.broadinstitute.org/software/mocha/) but you have to combine them with binaries for HTSlib 1.10.2 and BCFtools 1.10.2. I have a dockerfile for installing gtc2vcf (and MoChA) described [here](https://github.com/freeseek/mocha/tree/master/wdl#dockerfiles) but I am currently waiting for the next version of HTSlib/BCFtools to be released as some steps in the pipeline require features not available in the stable version of BCFtools.

Giulio

**Comment by aardes** [comment]
Dear Giulio,

Thanks a lot for the fast reply,

Kind regards
Amin

**Comment by erflynn** [comment]
Thanks for this resource!!

I set up a Singularity container based on the instructions, and I was able to get it to work for the autoconverter. Attaching the specification file since it took me a bit to set up in case this helps anyone [
[gtc2vcf_singularity.txt](https://github.com/freeseek/gtc2vcf/files/11290630/gtc2vcf_singularity.txt)
](url)

A couple caveats:
- I'm using version 1.16 of gtc2vcf and 1.17 of everything else -- I got it to work this way, so leaving it, but I know it should all be the same version
- I'm using Ubuntu 16.04 because that's what I could test with, I know there are newer versions.
- I many pieces into`/usr/local/bin/`, make sure this is in your `PATH`
- To run your own singularity build from the specification file, for autoconvert you will need to (1) make an account and download autoconvert from this site (https://support.illumina.com/array/array_software/beeline/downloads.html) and (2) upload this to a URL where you can download it. There is a TODO fill in section you will put it in

**Comment by freeseek** [comment]
A minimal image including autoconvert and gtc2vcf can be downloaded with the command:
```
singularity pull autoconvert.sif docker://us.gcr.io/mccarroll-mocha/autoconvert:1.16-20221221
```
Similarly an image including iaap-cli and gtc2vcf can be downloaded with the command:
```
singularity pull iaap_cli.sif docker://us.gcr.io/mccarroll-mocha/iaap_cli:1.16-20221221
```
Also an image that includes bwa, samtools, bcftools, gtc2vcf and mocha (but no plink) can be downloaded with the command:
```
singularity pull bcftools.sif docker://us.gcr.io/mccarroll-mocha/bcftools:1.16-20221221
```
The dockerfiles that created these images are detailed [here](https://github.com/freeseek/mochawdl)

**Comment by erflynn** [comment]
thanks so much for these resources! I did not realize they were available -- super helpful!
